### ISSUE TITLE
Add example to README and home/controllers.py

### ISSUE THREAD

**Issue by yanokwa** [alexpatow/xlsform-api#1]
Great work on this, @alexpatow! 

It'd be nice to have the exact syntax of how to post the file using curl. Without this, it's hard to know how to test.

I would guess `curl --request POST --data-binary "@/the/path/to/my/xlsx" http://127.0.0.1:5000/api/v1/convert` but that doesn't seem to work.

**Comment by alexpatow** [comment]
@yanokwa that's a great call, let me try to get that updated.

**Comment by alexpatow** [comment]
@yanokwa I think this is good to go. Can you please check again?

**Comment by yanokwa** [comment]
Fixed by #2
